# Accepting Arguments
import sys

name = sys.argv[1] # it will store the first thing you typed
print(sys.argv)
print(f"Hello {name}")

# do not run this through run button on the top right
# instead open a terminal and follow type these
# step 1 : cd ArgumentsFromCmd
# step 2 : python ARGS.py 
# anything you write after the ARGS.py will also print in the terminal this is accepting arguments
# through the terminal ( it will print out the list )